	kraft[playerid][53] = CreatePlayerTextDraw(playerid, 150.000000, 150.000000, "LD_SPAC:white");
	PlayerTextDrawLetterSize(playerid, kraft[playerid][53], 0.480000, 1.120000);
	PlayerTextDrawTextSize(playerid, kraft[playerid][53], 230.000000, 200.000000);
	PlayerTextDrawAlignment(playerid, kraft[playerid][53], 1);
	PlayerTextDrawColor(playerid, kraft[playerid][53], 0x111111FF);
	PlayerTextDrawUseBox(playerid, kraft[playerid][53], 0);
	PlayerTextDrawBoxColor(playerid, kraft[playerid][53], 0x80808080);
	PlayerTextDrawSetShadow(playerid, kraft[playerid][53], 2);
	PlayerTextDrawSetOutline(playerid, kraft[playerid][53], 0);
	PlayerTextDrawBackgroundColor(playerid, kraft[playerid][53], 0x000000FF);
	PlayerTextDrawFont(playerid, kraft[playerid][53], 4);
	PlayerTextDrawSetProportional(playerid, kraft[playerid][53], 1);
	PlayerTextDrawSetSelectable(playerid, kraft[playerid][53], 0);

	kraft[playerid][52] = CreatePlayerTextDraw(playerid, 150.000000, 173.600006, "LD_SPAC:white");
	PlayerTextDrawLetterSize(playerid, kraft[playerid][52], 0.480000, 1.120000);
	PlayerTextDrawTextSize(playerid, kraft[playerid][52], 230.000000, 1.000000);
	PlayerTextDrawAlignment(playerid, kraft[playerid][52], 1);
	PlayerTextDrawColor(playerid, kraft[playerid][52], PI[playerid][pColorInv]);
	PlayerTextDrawUseBox(playerid, kraft[playerid][52], 0);
	PlayerTextDrawBoxColor(playerid, kraft[playerid][52], 0x80808080);
	PlayerTextDrawSetShadow(playerid, kraft[playerid][52], 2);
	PlayerTextDrawSetOutline(playerid, kraft[playerid][52], 0);
	PlayerTextDrawBackgroundColor(playerid, kraft[playerid][52], 0x000000FF);
	PlayerTextDrawFont(playerid, kraft[playerid][52], 4);
	PlayerTextDrawSetProportional(playerid, kraft[playerid][52], 1);
	PlayerTextDrawSetSelectable(playerid, kraft[playerid][52], 0);

	kraft[playerid][51] = CreatePlayerTextDraw(playerid, 150.000000, 177.600006, "LD_SPAC:white");
	PlayerTextDrawLetterSize(playerid, kraft[playerid][51], 0.480000, 1.120000);
	PlayerTextDrawTextSize(playerid, kraft[playerid][51], 230.000000, 14.750000);
	PlayerTextDrawAlignment(playerid, kraft[playerid][51], 1);
	PlayerTextDrawColor(playerid, kraft[playerid][51], 0x050505FF);
	PlayerTextDrawUseBox(playerid, kraft[playerid][51], 0);
	PlayerTextDrawBoxColor(playerid, kraft[playerid][51], 0x80808080);
	PlayerTextDrawSetShadow(playerid, kraft[playerid][51], 2);
	PlayerTextDrawSetOutline(playerid, kraft[playerid][51], 0);
	PlayerTextDrawBackgroundColor(playerid, kraft[playerid][51], 0x000000FF);
	PlayerTextDrawFont(playerid, kraft[playerid][51], 4);
	PlayerTextDrawSetProportional(playerid, kraft[playerid][51], 1);
	PlayerTextDrawSetSelectable(playerid, kraft[playerid][51], 0);

	if(PI[playerid][pInvLang] == 0) kraft[playerid][50] = CreatePlayerTextDraw(playerid, 162.000000, 181.007278, "ACCESSORY");
	else kraft[playerid][50] = CreatePlayerTextDraw(playerid, 162.000000, 181.007278, FixText("AKCECCYAP‘"));
	PlayerTextDrawLetterSize(playerid, kraft[playerid][50], 0.134937, 0.793544);
	PlayerTextDrawTextSize(playerid, kraft[playerid][50], 194.182373, 6.348354);
	PlayerTextDrawAlignment(playerid, kraft[playerid][50], 1);
	PlayerTextDrawColor(playerid, kraft[playerid][50], 0xDA9949FF);
	PlayerTextDrawUseBox(playerid, kraft[playerid][50], 0);
	PlayerTextDrawBoxColor(playerid, kraft[playerid][50], 0x80808080);
	PlayerTextDrawSetShadow(playerid, kraft[playerid][50], 0);
	PlayerTextDrawSetOutline(playerid, kraft[playerid][50], 0);
	PlayerTextDrawBackgroundColor(playerid, kraft[playerid][50], 0x00000000);
	PlayerTextDrawFont(playerid, kraft[playerid][50], 2);
	PlayerTextDrawSetProportional(playerid, kraft[playerid][50], 1);
	PlayerTextDrawSetSelectable(playerid, kraft[playerid][50], 0);

	if(PI[playerid][pInvLang] == 0) kraft[playerid][49] = CreatePlayerTextDraw(playerid, 219.500000, 181.007278, "CLOTHES");
	else kraft[playerid][49] = CreatePlayerTextDraw(playerid, 219.500000, 181.007278, FixText("OѓE„ѓA"));
	PlayerTextDrawLetterSize(playerid, kraft[playerid][49], 0.134937, 0.793544);
	PlayerTextDrawTextSize(playerid, kraft[playerid][49], 244.530731, 6.348354);
	PlayerTextDrawAlignment(playerid, kraft[playerid][49], 1);
	PlayerTextDrawColor(playerid, kraft[playerid][49], 0x777777FF);
	PlayerTextDrawUseBox(playerid, kraft[playerid][49], 0);
	PlayerTextDrawBoxColor(playerid, kraft[playerid][49], 0x80808080);
	PlayerTextDrawSetShadow(playerid, kraft[playerid][49], 0);
	PlayerTextDrawSetOutline(playerid, kraft[playerid][49], 0);
	PlayerTextDrawBackgroundColor(playerid, kraft[playerid][49], 0x00000000);
	PlayerTextDrawFont(playerid, kraft[playerid][49], 2);
	PlayerTextDrawSetProportional(playerid, kraft[playerid][49], 1);
	PlayerTextDrawSetSelectable(playerid, kraft[playerid][49], 1);

	if(PI[playerid][pInvLang] == 0) kraft[playerid][48] = CreatePlayerTextDraw(playerid, 277.000000, 181.007278, "CHEMISTRY");
	else kraft[playerid][48] = CreatePlayerTextDraw(playerid, 277.000000, 181.007278, FixText("X…M…•"));
	PlayerTextDrawLetterSize(playerid, kraft[playerid][48], 0.134937, 0.793544);
	PlayerTextDrawTextSize(playerid, kraft[playerid][48], 309.182373, 6.348354);
	PlayerTextDrawAlignment(playerid, kraft[playerid][48], 1);
	PlayerTextDrawColor(playerid, kraft[playerid][48], 0x777777FF);
	PlayerTextDrawUseBox(playerid, kraft[playerid][48], 0);
	PlayerTextDrawBoxColor(playerid, kraft[playerid][48], 0x80808080);
	PlayerTextDrawSetShadow(playerid, kraft[playerid][48], 0);
	PlayerTextDrawSetOutline(playerid, kraft[playerid][48], 0);
	PlayerTextDrawBackgroundColor(playerid, kraft[playerid][48], 0x00000000);
	PlayerTextDrawFont(playerid, kraft[playerid][48], 2);
	PlayerTextDrawSetProportional(playerid, kraft[playerid][48], 1);
	PlayerTextDrawSetSelectable(playerid, kraft[playerid][48], 1);

	if(PI[playerid][pInvLang] == 0) kraft[playerid][47] = CreatePlayerTextDraw(playerid, 334.500000, 181.007278, "WORKING");
	else kraft[playerid][47] = CreatePlayerTextDraw(playerid, 334.500000, 181.007278, FixText("OЂPAЂOTKA"));
	PlayerTextDrawLetterSize(playerid, kraft[playerid][47], 0.134937, 0.793544);
	PlayerTextDrawTextSize(playerid, kraft[playerid][47], 359.530731, 6.348354);
	PlayerTextDrawAlignment(playerid, kraft[playerid][47], 1);
	PlayerTextDrawColor(playerid, kraft[playerid][47], 0x777777FF);
	PlayerTextDrawUseBox(playerid, kraft[playerid][47], 0);
	PlayerTextDrawBoxColor(playerid, kraft[playerid][47], 0x80808080);
	PlayerTextDrawSetShadow(playerid, kraft[playerid][47], 0);
	PlayerTextDrawSetOutline(playerid, kraft[playerid][47], 0);
	PlayerTextDrawBackgroundColor(playerid, kraft[playerid][47], 0x00000000);
	PlayerTextDrawFont(playerid, kraft[playerid][47], 2);
	PlayerTextDrawSetProportional(playerid, kraft[playerid][47], 1);
	PlayerTextDrawSetSelectable(playerid, kraft[playerid][47], 1);

	kraft[playerid][46] = CreatePlayerTextDraw(playerid, 156.000000, 198.350006, "LD_SPAC:white");
	PlayerTextDrawLetterSize(playerid, kraft[playerid][46], 0.480000, 1.120000);
	PlayerTextDrawTextSize(playerid, kraft[playerid][46], 92.000000, 13.111111);
	PlayerTextDrawAlignment(playerid, kraft[playerid][46], 1);
	PlayerTextDrawColor(playerid, kraft[playerid][46], PI[playerid][pColorInv]);
	PlayerTextDrawUseBox(playerid, kraft[playerid][46], 0);
	PlayerTextDrawBoxColor(playerid, kraft[playerid][46], 0x80808080);
	PlayerTextDrawSetShadow(playerid, kraft[playerid][46], 2);
	PlayerTextDrawSetOutline(playerid, kraft[playerid][46], 0);
	PlayerTextDrawBackgroundColor(playerid, kraft[playerid][46], 0x000000FF);
	PlayerTextDrawFont(playerid, kraft[playerid][46], 4);
	PlayerTextDrawSetProportional(playerid, kraft[playerid][46], 1);
	PlayerTextDrawSetSelectable(playerid, kraft[playerid][46], 0);

	kraft[playerid][45] = CreatePlayerTextDraw(playerid, 162.000000, 201.731384, "Kolonka");
	PlayerTextDrawLetterSize(playerid, kraft[playerid][45], 0.107949, 0.634835);
	PlayerTextDrawTextSize(playerid, kraft[playerid][45], 254.000000, 6.348354);
	PlayerTextDrawAlignment(playerid, kraft[playerid][45], 1);
	PlayerTextDrawColor(playerid, kraft[playerid][45], 0xFFFFFFFF);
	PlayerTextDrawUseBox(playerid, kraft[playerid][45], 0);
	PlayerTextDrawBoxColor(playerid, kraft[playerid][45], 0x80808080);
	PlayerTextDrawSetShadow(playerid, kraft[playerid][45], 0);
	PlayerTextDrawSetOutline(playerid, kraft[playerid][45], 0);
	PlayerTextDrawBackgroundColor(playerid, kraft[playerid][45], 0x00000000);
	PlayerTextDrawFont(playerid, kraft[playerid][45], 2);
	PlayerTextDrawSetProportional(playerid, kraft[playerid][45], 1);
	PlayerTextDrawSetSelectable(playerid, kraft[playerid][45], 0);

	kraft[playerid][44] = CreatePlayerTextDraw(playerid, 156.000000, 211.461121, "LD_SPAC:white");
	PlayerTextDrawLetterSize(playerid, kraft[playerid][44], 0.480000, 1.120000);
	PlayerTextDrawTextSize(playerid, kraft[playerid][44], 92.000000, 13.111111);
	PlayerTextDrawAlignment(playerid, kraft[playerid][44], 1);
	PlayerTextDrawColor(playerid, kraft[playerid][44], 0x050505FF);
	PlayerTextDrawUseBox(playerid, kraft[playerid][44], 0);
	PlayerTextDrawBoxColor(playerid, kraft[playerid][44], 0x80808080);
	PlayerTextDrawSetShadow(playerid, kraft[playerid][44], 2);
	PlayerTextDrawSetOutline(playerid, kraft[playerid][44], 0);
	PlayerTextDrawBackgroundColor(playerid, kraft[playerid][44], 0x000000FF);
	PlayerTextDrawFont(playerid, kraft[playerid][44], 4);
	PlayerTextDrawSetProportional(playerid, kraft[playerid][44], 1);
	PlayerTextDrawSetSelectable(playerid, kraft[playerid][44], 0);

	kraft[playerid][43] = CreatePlayerTextDraw(playerid, 162.000000, 214.842499, "Extinguisher");
	PlayerTextDrawLetterSize(playerid, kraft[playerid][43], 0.107949, 0.634835);
	PlayerTextDrawTextSize(playerid, kraft[playerid][43], 254.000000, 6.348354);
	PlayerTextDrawAlignment(playerid, kraft[playerid][43], 1);
	PlayerTextDrawColor(playerid, kraft[playerid][43], 0x777777FF);
	PlayerTextDrawUseBox(playerid, kraft[playerid][43], 0);
	PlayerTextDrawBoxColor(playerid, kraft[playerid][43], 0x80808080);
	PlayerTextDrawSetShadow(playerid, kraft[playerid][43], 0);
	PlayerTextDrawSetOutline(playerid, kraft[playerid][43], 0);
	PlayerTextDrawBackgroundColor(playerid, kraft[playerid][43], 0x00000000);
	PlayerTextDrawFont(playerid, kraft[playerid][43], 2);
	PlayerTextDrawSetProportional(playerid, kraft[playerid][43], 1);
	PlayerTextDrawSetSelectable(playerid, kraft[playerid][43], 67);

	kraft[playerid][42] = CreatePlayerTextDraw(playerid, 156.000000, 224.572235, "LD_SPAC:white");
	PlayerTextDrawLetterSize(playerid, kraft[playerid][42], 0.480000, 1.120000);
	PlayerTextDrawTextSize(playerid, kraft[playerid][42], 92.000000, 13.111111);
	PlayerTextDrawAlignment(playerid, kraft[playerid][42], 1);
	PlayerTextDrawColor(playerid, kraft[playerid][42], 0x050505FF);
	PlayerTextDrawUseBox(playerid, kraft[playerid][42], 0);
	PlayerTextDrawBoxColor(playerid, kraft[playerid][42], 0x80808080);
	PlayerTextDrawSetShadow(playerid, kraft[playerid][42], 2);
	PlayerTextDrawSetOutline(playerid, kraft[playerid][42], 0);
	PlayerTextDrawBackgroundColor(playerid, kraft[playerid][42], 0x000000FF);
	PlayerTextDrawFont(playerid, kraft[playerid][42], 4);
	PlayerTextDrawSetProportional(playerid, kraft[playerid][42], 1);
	PlayerTextDrawSetSelectable(playerid, kraft[playerid][42], 0);

	kraft[playerid][41] = CreatePlayerTextDraw(playerid, 162.000000, 227.953613, "Bat with nails");
	PlayerTextDrawLetterSize(playerid, kraft[playerid][41], 0.107949, 0.634835);
	PlayerTextDrawTextSize(playerid, kraft[playerid][41], 254.000000, 6.348354);
	PlayerTextDrawAlignment(playerid, kraft[playerid][41], 1);
	PlayerTextDrawColor(playerid, kraft[playerid][41], 0x777777FF);
	PlayerTextDrawUseBox(playerid, kraft[playerid][41], 0);
	PlayerTextDrawBoxColor(playerid, kraft[playerid][41], 0x80808080);
	PlayerTextDrawSetShadow(playerid, kraft[playerid][41], 0);
	PlayerTextDrawSetOutline(playerid, kraft[playerid][41], 0);
	PlayerTextDrawBackgroundColor(playerid, kraft[playerid][41], 0x00000000);
	PlayerTextDrawFont(playerid, kraft[playerid][41], 2);
	PlayerTextDrawSetProportional(playerid, kraft[playerid][41], 1);
	PlayerTextDrawSetSelectable(playerid, kraft[playerid][41], 68);

	kraft[playerid][40] = CreatePlayerTextDraw(playerid, 156.000000, 237.683334, "LD_SPAC:white");
	PlayerTextDrawLetterSize(playerid, kraft[playerid][40], 0.480000, 1.120000);
	PlayerTextDrawTextSize(playerid, kraft[playerid][40], 92.000000, 13.111111);
	PlayerTextDrawAlignment(playerid, kraft[playerid][40], 1);
	PlayerTextDrawColor(playerid, kraft[playerid][40], 0x050505FF);
	PlayerTextDrawUseBox(playerid, kraft[playerid][40], 0);
	PlayerTextDrawBoxColor(playerid, kraft[playerid][40], 0x80808080);
	PlayerTextDrawSetShadow(playerid, kraft[playerid][40], 2);
	PlayerTextDrawSetOutline(playerid, kraft[playerid][40], 0);
	PlayerTextDrawBackgroundColor(playerid, kraft[playerid][40], 0x000000FF);
	PlayerTextDrawFont(playerid, kraft[playerid][40], 4);
	PlayerTextDrawSetProportional(playerid, kraft[playerid][40], 1);
	PlayerTextDrawSetSelectable(playerid, kraft[playerid][40], 0);

	kraft[playerid][39] = CreatePlayerTextDraw(playerid, 162.000000, 241.064713, "Sword");
	PlayerTextDrawLetterSize(playerid, kraft[playerid][39], 0.107949, 0.634835);
	PlayerTextDrawTextSize(playerid, kraft[playerid][39], 254.000000, 6.348354);
	PlayerTextDrawAlignment(playerid, kraft[playerid][39], 1);
	PlayerTextDrawColor(playerid, kraft[playerid][39], 0x777777FF);
	PlayerTextDrawUseBox(playerid, kraft[playerid][39], 0);
	PlayerTextDrawBoxColor(playerid, kraft[playerid][39], 0x80808080);
	PlayerTextDrawSetShadow(playerid, kraft[playerid][39], 0);
	PlayerTextDrawSetOutline(playerid, kraft[playerid][39], 0);
	PlayerTextDrawBackgroundColor(playerid, kraft[playerid][39], 0x00000000);
	PlayerTextDrawFont(playerid, kraft[playerid][39], 2);
	PlayerTextDrawSetProportional(playerid, kraft[playerid][39], 1);
	PlayerTextDrawSetSelectable(playerid, kraft[playerid][39], 69);

	kraft[playerid][38] = CreatePlayerTextDraw(playerid, 156.000000, 250.794449, "LD_SPAC:white");
	PlayerTextDrawLetterSize(playerid, kraft[playerid][38], 0.480000, 1.120000);
	PlayerTextDrawTextSize(playerid, kraft[playerid][38], 92.000000, 13.111111);
	PlayerTextDrawAlignment(playerid, kraft[playerid][38], 1);
	PlayerTextDrawColor(playerid, kraft[playerid][38], 0x050505FF);
	PlayerTextDrawUseBox(playerid, kraft[playerid][38], 0);
	PlayerTextDrawBoxColor(playerid, kraft[playerid][38], 0x80808080);
	PlayerTextDrawSetShadow(playerid, kraft[playerid][38], 2);
	PlayerTextDrawSetOutline(playerid, kraft[playerid][38], 0);
	PlayerTextDrawBackgroundColor(playerid, kraft[playerid][38], 0x000000FF);
	PlayerTextDrawFont(playerid, kraft[playerid][38], 4);
	PlayerTextDrawSetProportional(playerid, kraft[playerid][38], 1);
	PlayerTextDrawSetSelectable(playerid, kraft[playerid][38], 0);

	kraft[playerid][37] = CreatePlayerTextDraw(playerid, 162.000000, 254.175827, "Hammer");
	PlayerTextDrawLetterSize(playerid, kraft[playerid][37], 0.107949, 0.634835);
	PlayerTextDrawTextSize(playerid, kraft[playerid][37], 254.000000, 6.348354);
	PlayerTextDrawAlignment(playerid, kraft[playerid][37], 1);
	PlayerTextDrawColor(playerid, kraft[playerid][37], 0x777777FF);
	PlayerTextDrawUseBox(playerid, kraft[playerid][37], 0);
	PlayerTextDrawBoxColor(playerid, kraft[playerid][37], 0x80808080);
	PlayerTextDrawSetShadow(playerid, kraft[playerid][37], 0);
	PlayerTextDrawSetOutline(playerid, kraft[playerid][37], 0);
	PlayerTextDrawBackgroundColor(playerid, kraft[playerid][37], 0x00000000);
	PlayerTextDrawFont(playerid, kraft[playerid][37], 2);
	PlayerTextDrawSetProportional(playerid, kraft[playerid][37], 1);
	PlayerTextDrawSetSelectable(playerid, kraft[playerid][37], 70);

	kraft[playerid][36] = CreatePlayerTextDraw(playerid, 156.000000, 263.905579, "LD_SPAC:white");
	PlayerTextDrawLetterSize(playerid, kraft[playerid][36], 0.480000, 1.120000);
	PlayerTextDrawTextSize(playerid, kraft[playerid][36], 92.000000, 13.111111);
	PlayerTextDrawAlignment(playerid, kraft[playerid][36], 1);
	PlayerTextDrawColor(playerid, kraft[playerid][36], 0x050505FF);
	PlayerTextDrawUseBox(playerid, kraft[playerid][36], 0);
	PlayerTextDrawBoxColor(playerid, kraft[playerid][36], 0x80808080);
	PlayerTextDrawSetShadow(playerid, kraft[playerid][36], 2);
	PlayerTextDrawSetOutline(playerid, kraft[playerid][36], 0);
	PlayerTextDrawBackgroundColor(playerid, kraft[playerid][36], 0x000000FF);
	PlayerTextDrawFont(playerid, kraft[playerid][36], 4);
	PlayerTextDrawSetProportional(playerid, kraft[playerid][36], 1);
	PlayerTextDrawSetSelectable(playerid, kraft[playerid][36], 0);

	kraft[playerid][35] = CreatePlayerTextDraw(playerid, 162.000000, 267.286957, "Maska CJ");
	PlayerTextDrawLetterSize(playerid, kraft[playerid][35], 0.107949, 0.634835);
	PlayerTextDrawTextSize(playerid, kraft[playerid][35], 254.000000, 6.348354);
	PlayerTextDrawAlignment(playerid, kraft[playerid][35], 1);
	PlayerTextDrawColor(playerid, kraft[playerid][35], 0x777777FF);
	PlayerTextDrawUseBox(playerid, kraft[playerid][35], 0);
	PlayerTextDrawBoxColor(playerid, kraft[playerid][35], 0x80808080);
	PlayerTextDrawSetShadow(playerid, kraft[playerid][35], 0);
	PlayerTextDrawSetOutline(playerid, kraft[playerid][35], 0);
	PlayerTextDrawBackgroundColor(playerid, kraft[playerid][35], 0x00000000);
	PlayerTextDrawFont(playerid, kraft[playerid][35], 2);
	PlayerTextDrawSetProportional(playerid, kraft[playerid][35], 1);
	PlayerTextDrawSetSelectable(playerid, kraft[playerid][35], 71);

	kraft[playerid][34] = CreatePlayerTextDraw(playerid, 156.000000, 277.016663, "LD_SPAC:white");
	PlayerTextDrawLetterSize(playerid, kraft[playerid][34], 0.480000, 1.120000);
	PlayerTextDrawTextSize(playerid, kraft[playerid][34], 92.000000, 13.111111);
	PlayerTextDrawAlignment(playerid, kraft[playerid][34], 1);
	PlayerTextDrawColor(playerid, kraft[playerid][34], 0x050505FF);
	PlayerTextDrawUseBox(playerid, kraft[playerid][34], 0);
	PlayerTextDrawBoxColor(playerid, kraft[playerid][34], 0x80808080);
	PlayerTextDrawSetShadow(playerid, kraft[playerid][34], 2);
	PlayerTextDrawSetOutline(playerid, kraft[playerid][34], 0);
	PlayerTextDrawBackgroundColor(playerid, kraft[playerid][34], 0x000000FF);
	PlayerTextDrawFont(playerid, kraft[playerid][34], 4);
	PlayerTextDrawSetProportional(playerid, kraft[playerid][34], 1);
	PlayerTextDrawSetSelectable(playerid, kraft[playerid][34], 0);

	kraft[playerid][33] = CreatePlayerTextDraw(playerid, 162.000000, 280.398041, "Red suitcase");
	PlayerTextDrawLetterSize(playerid, kraft[playerid][33], 0.107949, 0.634835);
	PlayerTextDrawTextSize(playerid, kraft[playerid][33], 254.000000, 6.348354);
	PlayerTextDrawAlignment(playerid, kraft[playerid][33], 1);
	PlayerTextDrawColor(playerid, kraft[playerid][33], 0x777777FF);
	PlayerTextDrawUseBox(playerid, kraft[playerid][33], 0);
	PlayerTextDrawBoxColor(playerid, kraft[playerid][33], 0x80808080);
	PlayerTextDrawSetShadow(playerid, kraft[playerid][33], 0);
	PlayerTextDrawSetOutline(playerid, kraft[playerid][33], 0);
	PlayerTextDrawBackgroundColor(playerid, kraft[playerid][33], 0x00000000);
	PlayerTextDrawFont(playerid, kraft[playerid][33], 2);
	PlayerTextDrawSetProportional(playerid, kraft[playerid][33], 1);
	PlayerTextDrawSetSelectable(playerid, kraft[playerid][33], 72);

	kraft[playerid][32] = CreatePlayerTextDraw(playerid, 156.000000, 290.127777, "LD_SPAC:white");
	PlayerTextDrawLetterSize(playerid, kraft[playerid][32], 0.480000, 1.120000);
	PlayerTextDrawTextSize(playerid, kraft[playerid][32], 92.000000, 13.111111);
	PlayerTextDrawAlignment(playerid, kraft[playerid][32], 1);
	PlayerTextDrawColor(playerid, kraft[playerid][32], 0x050505FF);
	PlayerTextDrawUseBox(playerid, kraft[playerid][32], 0);
	PlayerTextDrawBoxColor(playerid, kraft[playerid][32], 0x80808080);
	PlayerTextDrawSetShadow(playerid, kraft[playerid][32], 2);
	PlayerTextDrawSetOutline(playerid, kraft[playerid][32], 0);
	PlayerTextDrawBackgroundColor(playerid, kraft[playerid][32], 0x000000FF);
	PlayerTextDrawFont(playerid, kraft[playerid][32], 4);
	PlayerTextDrawSetProportional(playerid, kraft[playerid][32], 1);
	PlayerTextDrawSetSelectable(playerid, kraft[playerid][32], 0);

	kraft[playerid][31] = CreatePlayerTextDraw(playerid, 162.000000, 293.509155, "Helmet");
	PlayerTextDrawLetterSize(playerid, kraft[playerid][31], 0.107949, 0.634835);
	PlayerTextDrawTextSize(playerid, kraft[playerid][31], 254.000000, 6.348354);
	PlayerTextDrawAlignment(playerid, kraft[playerid][31], 1);
	PlayerTextDrawColor(playerid, kraft[playerid][31], 0x777777FF);
	PlayerTextDrawUseBox(playerid, kraft[playerid][31], 0);
	PlayerTextDrawBoxColor(playerid, kraft[playerid][31], 0x80808080);
	PlayerTextDrawSetShadow(playerid, kraft[playerid][31], 0);
	PlayerTextDrawSetOutline(playerid, kraft[playerid][31], 0);
	PlayerTextDrawBackgroundColor(playerid, kraft[playerid][31], 0x00000000);
	PlayerTextDrawFont(playerid, kraft[playerid][31], 2);
	PlayerTextDrawSetProportional(playerid, kraft[playerid][31], 1);
	PlayerTextDrawSetSelectable(playerid, kraft[playerid][31], 73);

	kraft[playerid][30] = CreatePlayerTextDraw(playerid, 156.000000, 303.238892, "LD_SPAC:white");
	PlayerTextDrawLetterSize(playerid, kraft[playerid][30], 0.480000, 1.120000);
	PlayerTextDrawTextSize(playerid, kraft[playerid][30], 92.000000, 13.111111);
	PlayerTextDrawAlignment(playerid, kraft[playerid][30], 1);
	PlayerTextDrawColor(playerid, kraft[playerid][30], 0x050505FF);
	PlayerTextDrawUseBox(playerid, kraft[playerid][30], 0);
	PlayerTextDrawBoxColor(playerid, kraft[playerid][30], 0x80808080);
	PlayerTextDrawSetShadow(playerid, kraft[playerid][30], 2);
	PlayerTextDrawSetOutline(playerid, kraft[playerid][30], 0);
	PlayerTextDrawBackgroundColor(playerid, kraft[playerid][30], 0x000000FF);
	PlayerTextDrawFont(playerid, kraft[playerid][30], 4);
	PlayerTextDrawSetProportional(playerid, kraft[playerid][30], 1);
	PlayerTextDrawSetSelectable(playerid, kraft[playerid][30], 0);

	kraft[playerid][29] = CreatePlayerTextDraw(playerid, 162.000000, 306.620270, "Maska");
	PlayerTextDrawLetterSize(playerid, kraft[playerid][29], 0.107949, 0.634835);
	PlayerTextDrawTextSize(playerid, kraft[playerid][29], 254.000000, 6.348354);
	PlayerTextDrawAlignment(playerid, kraft[playerid][29], 1);
	PlayerTextDrawColor(playerid, kraft[playerid][29], 0x777777FF);
	PlayerTextDrawUseBox(playerid, kraft[playerid][29], 0);
	PlayerTextDrawBoxColor(playerid, kraft[playerid][29], 0x80808080);
	PlayerTextDrawSetShadow(playerid, kraft[playerid][29], 0);
	PlayerTextDrawSetOutline(playerid, kraft[playerid][29], 0);
	PlayerTextDrawBackgroundColor(playerid, kraft[playerid][29], 0x00000000);
	PlayerTextDrawFont(playerid, kraft[playerid][29], 2);
	PlayerTextDrawSetProportional(playerid, kraft[playerid][29], 1);
	PlayerTextDrawSetSelectable(playerid, kraft[playerid][29], 74);

	kraft[playerid][28] = CreatePlayerTextDraw(playerid, 156.000000, 316.350006, "LD_SPAC:white");
	PlayerTextDrawLetterSize(playerid, kraft[playerid][28], 0.480000, 1.120000);
	PlayerTextDrawTextSize(playerid, kraft[playerid][28], 92.000000, 13.111111);
	PlayerTextDrawAlignment(playerid, kraft[playerid][28], 1);
	PlayerTextDrawColor(playerid, kraft[playerid][28], 0x050505FF);
	PlayerTextDrawUseBox(playerid, kraft[playerid][28], 0);
	PlayerTextDrawBoxColor(playerid, kraft[playerid][28], 0x80808080);
	PlayerTextDrawSetShadow(playerid, kraft[playerid][28], 2);
	PlayerTextDrawSetOutline(playerid, kraft[playerid][28], 0);
	PlayerTextDrawBackgroundColor(playerid, kraft[playerid][28], 0x000000FF);
	PlayerTextDrawFont(playerid, kraft[playerid][28], 4);
	PlayerTextDrawSetProportional(playerid, kraft[playerid][28], 1);
	PlayerTextDrawSetSelectable(playerid, kraft[playerid][28], 0);

	kraft[playerid][27] = CreatePlayerTextDraw(playerid, 162.000000, 319.731384, "Maska");
	PlayerTextDrawLetterSize(playerid, kraft[playerid][27], 0.107949, 0.634835);
	PlayerTextDrawTextSize(playerid, kraft[playerid][27], 254.000000, 6.348354);
	PlayerTextDrawAlignment(playerid, kraft[playerid][27], 1);
	PlayerTextDrawColor(playerid, kraft[playerid][27], 0x777777FF);
	PlayerTextDrawUseBox(playerid, kraft[playerid][27], 0);
	PlayerTextDrawBoxColor(playerid, kraft[playerid][27], 0x80808080);
	PlayerTextDrawSetShadow(playerid, kraft[playerid][27], 0);
	PlayerTextDrawSetOutline(playerid, kraft[playerid][27], 0);
	PlayerTextDrawBackgroundColor(playerid, kraft[playerid][27], 0x00000000);
	PlayerTextDrawFont(playerid, kraft[playerid][27], 2);
	PlayerTextDrawSetProportional(playerid, kraft[playerid][27], 1);
	PlayerTextDrawSetSelectable(playerid, kraft[playerid][27], 75);

	kraft[playerid][26] = CreatePlayerTextDraw(playerid, 156.000000, 329.461121, "LD_SPAC:white");
	PlayerTextDrawLetterSize(playerid, kraft[playerid][26], 0.480000, 1.120000);
	PlayerTextDrawTextSize(playerid, kraft[playerid][26], 92.000000, 13.111111);
	PlayerTextDrawAlignment(playerid, kraft[playerid][26], 1);
	PlayerTextDrawColor(playerid, kraft[playerid][26], 0x050505FF);
	PlayerTextDrawUseBox(playerid, kraft[playerid][26], 0);
	PlayerTextDrawBoxColor(playerid, kraft[playerid][26], 0x80808080);
	PlayerTextDrawSetShadow(playerid, kraft[playerid][26], 2);
	PlayerTextDrawSetOutline(playerid, kraft[playerid][26], 0);
	PlayerTextDrawBackgroundColor(playerid, kraft[playerid][26], 0x000000FF);
	PlayerTextDrawFont(playerid, kraft[playerid][26], 4);
	PlayerTextDrawSetProportional(playerid, kraft[playerid][26], 1);
	PlayerTextDrawSetSelectable(playerid, kraft[playerid][26], 0);

	kraft[playerid][25] = CreatePlayerTextDraw(playerid, 186.666672, 332.842499, "<");
	PlayerTextDrawLetterSize(playerid, kraft[playerid][25], 0.107949, 0.634835);
	PlayerTextDrawTextSize(playerid, kraft[playerid][25], 189.905151, 6.348354);
	PlayerTextDrawAlignment(playerid, kraft[playerid][25], 1);
	PlayerTextDrawColor(playerid, kraft[playerid][25], 0xDA9949FF);
	PlayerTextDrawUseBox(playerid, kraft[playerid][25], 0);
	PlayerTextDrawBoxColor(playerid, kraft[playerid][25], 0x80808080);
	PlayerTextDrawSetShadow(playerid, kraft[playerid][25], 0);
	PlayerTextDrawSetOutline(playerid, kraft[playerid][25], 0);
	PlayerTextDrawBackgroundColor(playerid, kraft[playerid][25], 0x00000000);
	PlayerTextDrawFont(playerid, kraft[playerid][25], 2);
	PlayerTextDrawSetProportional(playerid, kraft[playerid][25], 1);
	PlayerTextDrawSetSelectable(playerid, kraft[playerid][25], 1);

	kraft[playerid][24] = CreatePlayerTextDraw(playerid, 202.000000, 332.842499, "1 / 2");
	PlayerTextDrawLetterSize(playerid, kraft[playerid][24], 0.107949, 0.634835);
	PlayerTextDrawTextSize(playerid, kraft[playerid][24], 1280.000000, 1280.000000);
	PlayerTextDrawAlignment(playerid, kraft[playerid][24], 2);
	PlayerTextDrawColor(playerid, kraft[playerid][24], 0xDA9949FF);
	PlayerTextDrawUseBox(playerid, kraft[playerid][24], 0);
	PlayerTextDrawBoxColor(playerid, kraft[playerid][24], 0x80808080);
	PlayerTextDrawSetShadow(playerid, kraft[playerid][24], 0);
	PlayerTextDrawSetOutline(playerid, kraft[playerid][24], 0);
	PlayerTextDrawBackgroundColor(playerid, kraft[playerid][24], 0x00000000);
	PlayerTextDrawFont(playerid, kraft[playerid][24], 2);
	PlayerTextDrawSetProportional(playerid, kraft[playerid][24], 1);
	PlayerTextDrawSetSelectable(playerid, kraft[playerid][24], 0);

	kraft[playerid][23] = CreatePlayerTextDraw(playerid, 214.526642, 332.842499, ">");
	PlayerTextDrawLetterSize(playerid, kraft[playerid][23], 0.107949, 0.634835);
	PlayerTextDrawTextSize(playerid, kraft[playerid][23], 217.765121, 6.348354);
	PlayerTextDrawAlignment(playerid, kraft[playerid][23], 1);
	PlayerTextDrawColor(playerid, kraft[playerid][23], 0xDA9949FF);
	PlayerTextDrawUseBox(playerid, kraft[playerid][23], 0);
	PlayerTextDrawBoxColor(playerid, kraft[playerid][23], 0x80808080);
	PlayerTextDrawSetShadow(playerid, kraft[playerid][23], 0);
	PlayerTextDrawSetOutline(playerid, kraft[playerid][23], 0);
	PlayerTextDrawBackgroundColor(playerid, kraft[playerid][23], 0x00000000);
	PlayerTextDrawFont(playerid, kraft[playerid][23], 2);
	PlayerTextDrawSetProportional(playerid, kraft[playerid][23], 1);
	PlayerTextDrawSetSelectable(playerid, kraft[playerid][23], 1);

	kraft[playerid][22] = CreatePlayerTextDraw(playerid, 254.000000, 198.350006, "LD_SPAC:white");
	PlayerTextDrawLetterSize(playerid, kraft[playerid][22], 0.480000, 1.120000);
	PlayerTextDrawTextSize(playerid, kraft[playerid][22], 120.000000, 144.222229);
	PlayerTextDrawAlignment(playerid, kraft[playerid][22], 1);
	PlayerTextDrawColor(playerid, kraft[playerid][22], 0x050505FF);
	PlayerTextDrawUseBox(playerid, kraft[playerid][22], 0);
	PlayerTextDrawBoxColor(playerid, kraft[playerid][22], 0x80808080);
	PlayerTextDrawSetShadow(playerid, kraft[playerid][22], 2);
	PlayerTextDrawSetOutline(playerid, kraft[playerid][22], 0);
	PlayerTextDrawBackgroundColor(playerid, kraft[playerid][22], 0x000000FF);
	PlayerTextDrawFont(playerid, kraft[playerid][22], 4);
	PlayerTextDrawSetProportional(playerid, kraft[playerid][22], 1);
	PlayerTextDrawSetSelectable(playerid, kraft[playerid][22], 0);

	kraft[playerid][21] = CreatePlayerTextDraw(playerid, 257.000000, 201.350006, "LD_SPAC:white");
	PlayerTextDrawLetterSize(playerid, kraft[playerid][21], 0.480000, 1.120000);
	PlayerTextDrawTextSize(playerid, kraft[playerid][21], 31.875000, 36.875000);
	PlayerTextDrawAlignment(playerid, kraft[playerid][21], 1);
	PlayerTextDrawColor(playerid, kraft[playerid][21], 0xFFFFFFFF);
	PlayerTextDrawUseBox(playerid, kraft[playerid][21], 0);
	PlayerTextDrawBoxColor(playerid, kraft[playerid][21], 0x80808080);
	PlayerTextDrawSetShadow(playerid, kraft[playerid][21], 2);
	PlayerTextDrawSetOutline(playerid, kraft[playerid][21], 0);
	PlayerTextDrawBackgroundColor(playerid, kraft[playerid][21], 0x333333FF);
	PlayerTextDrawFont(playerid, kraft[playerid][21], 5);
	PlayerTextDrawSetProportional(playerid, kraft[playerid][21], 1);
	PlayerTextDrawSetSelectable(playerid, kraft[playerid][21], 0);
	PlayerTextDrawSetPreviewModel(playerid, kraft[playerid][21], 2102);
	PlayerTextDrawSetPreviewRot(playerid, kraft[playerid][21], 0.000000, 0.000000, 193.000000, 0.872784);

	kraft[playerid][20] = CreatePlayerTextDraw(playerid, 331.437500, 204.350006, "Kolonka");
	PlayerTextDrawLetterSize(playerid, kraft[playerid][20], 0.107949, 0.634835);
	PlayerTextDrawTextSize(playerid, kraft[playerid][20], 1280.000000, 1280.000000);
	PlayerTextDrawAlignment(playerid, kraft[playerid][20], 2);
	PlayerTextDrawColor(playerid, kraft[playerid][20], 0xFFFFFFFF);
	PlayerTextDrawUseBox(playerid, kraft[playerid][20], 0);
	PlayerTextDrawBoxColor(playerid, kraft[playerid][20], 0x80808080);
	PlayerTextDrawSetShadow(playerid, kraft[playerid][20], 0);
	PlayerTextDrawSetOutline(playerid, kraft[playerid][20], 0);
	PlayerTextDrawBackgroundColor(playerid, kraft[playerid][20], 0x00000000);
	PlayerTextDrawFont(playerid, kraft[playerid][20], 2);
	PlayerTextDrawSetProportional(playerid, kraft[playerid][20], 1);
	PlayerTextDrawSetSelectable(playerid, kraft[playerid][20], 0);

	kraft[playerid][19] = CreatePlayerTextDraw(playerid, 257.000000, 250.225006, "LD_SPAC:white");
	PlayerTextDrawLetterSize(playerid, kraft[playerid][19], 0.480000, 1.120000);
	PlayerTextDrawTextSize(playerid, kraft[playerid][19], 114.000000, 1.000000);
	PlayerTextDrawAlignment(playerid, kraft[playerid][19], 1);
	PlayerTextDrawColor(playerid, kraft[playerid][19], PI[playerid][pColorInv]);
	PlayerTextDrawUseBox(playerid, kraft[playerid][19], 0);
	PlayerTextDrawBoxColor(playerid, kraft[playerid][19], 0x80808080);
	PlayerTextDrawSetShadow(playerid, kraft[playerid][19], 2);
	PlayerTextDrawSetOutline(playerid, kraft[playerid][19], 0);
	PlayerTextDrawBackgroundColor(playerid, kraft[playerid][19], 0x000000FF);
	PlayerTextDrawFont(playerid, kraft[playerid][19], 4);
	PlayerTextDrawSetProportional(playerid, kraft[playerid][19], 1);
	PlayerTextDrawSetSelectable(playerid, kraft[playerid][19], 0);

	if(PI[playerid][pInvLang] == 0) kraft[playerid][18] = CreatePlayerTextDraw(playerid, 260.000000, 257.225006, "TREBOVANIYe:");
	else kraft[playerid][18] = CreatePlayerTextDraw(playerid, 260.000000, 257.225006, FixText("TPEЂOBAH…"));
	PlayerTextDrawLetterSize(playerid, kraft[playerid][18], 0.134937, 0.793544);
	PlayerTextDrawTextSize(playerid, kraft[playerid][18], 1280.000000, 1280.000000);
	PlayerTextDrawAlignment(playerid, kraft[playerid][18], 1);
	PlayerTextDrawColor(playerid, kraft[playerid][18], 0xDA9949FF);
	PlayerTextDrawUseBox(playerid, kraft[playerid][18], 0);
	PlayerTextDrawBoxColor(playerid, kraft[playerid][18], 0x80808080);
	PlayerTextDrawSetShadow(playerid, kraft[playerid][18], 0);
	PlayerTextDrawSetOutline(playerid, kraft[playerid][18], 0);
	PlayerTextDrawBackgroundColor(playerid, kraft[playerid][18], 0x00000000);
	PlayerTextDrawFont(playerid, kraft[playerid][18], 2);
	PlayerTextDrawSetProportional(playerid, kraft[playerid][18], 1);
	PlayerTextDrawSetSelectable(playerid, kraft[playerid][18], 0);

	kraft[playerid][17] = CreatePlayerTextDraw(playerid, 260.000000, 271.160461, "LD_SPAC:white");
	PlayerTextDrawLetterSize(playerid, kraft[playerid][17], 0.480000, 1.120000);
	PlayerTextDrawTextSize(playerid, kraft[playerid][17], 22.500000, 26.029411);
	PlayerTextDrawAlignment(playerid, kraft[playerid][17], 1);
	PlayerTextDrawColor(playerid, kraft[playerid][17], 0x666666FF);
	PlayerTextDrawUseBox(playerid, kraft[playerid][17], 0);
	PlayerTextDrawBoxColor(playerid, kraft[playerid][17], 0x80808080);
	PlayerTextDrawSetShadow(playerid, kraft[playerid][17], 2);
	PlayerTextDrawSetOutline(playerid, kraft[playerid][17], 0);
	PlayerTextDrawBackgroundColor(playerid, kraft[playerid][17], 0x333333FF);
	PlayerTextDrawFont(playerid, kraft[playerid][17], 5);
	PlayerTextDrawSetProportional(playerid, kraft[playerid][17], 1);
	PlayerTextDrawSetSelectable(playerid, kraft[playerid][17], 1);
	PlayerTextDrawSetPreviewModel(playerid, kraft[playerid][17], 1304);
	PlayerTextDrawSetPreviewRot(playerid, kraft[playerid][17], 236.000000, 0.000000, 0.000000, 1.558915);

	kraft[playerid][16] = CreatePlayerTextDraw(playerid, 271.250000, 290.899597, "~r~0 / 30");
	PlayerTextDrawLetterSize(playerid, kraft[playerid][16], 0.089958, 0.529030);
	PlayerTextDrawTextSize(playerid, kraft[playerid][16], 1280.000000, 1280.000000);
	PlayerTextDrawAlignment(playerid, kraft[playerid][16], 2);
	PlayerTextDrawColor(playerid, kraft[playerid][16], 0xFFFFFFFF);
	PlayerTextDrawUseBox(playerid, kraft[playerid][16], 0);
	PlayerTextDrawBoxColor(playerid, kraft[playerid][16], 0x80808080);
	PlayerTextDrawSetShadow(playerid, kraft[playerid][16], 0);
	PlayerTextDrawSetOutline(playerid, kraft[playerid][16], 0);
	PlayerTextDrawBackgroundColor(playerid, kraft[playerid][16], 0x00000000);
	PlayerTextDrawFont(playerid, kraft[playerid][16], 2);
	PlayerTextDrawSetProportional(playerid, kraft[playerid][16], 1);
	PlayerTextDrawSetSelectable(playerid, kraft[playerid][16], 0);

	kraft[playerid][15] = CreatePlayerTextDraw(playerid, 288.500000, 271.160461, "LD_SPAC:white");
	PlayerTextDrawLetterSize(playerid, kraft[playerid][15], 0.480000, 1.120000);
	PlayerTextDrawTextSize(playerid, kraft[playerid][15], 22.500000, 26.029411);
	PlayerTextDrawAlignment(playerid, kraft[playerid][15], 1);
	PlayerTextDrawColor(playerid, kraft[playerid][15], 0x666666FF);
	PlayerTextDrawUseBox(playerid, kraft[playerid][15], 0);
	PlayerTextDrawBoxColor(playerid, kraft[playerid][15], 0x80808080);
	PlayerTextDrawSetShadow(playerid, kraft[playerid][15], 2);
	PlayerTextDrawSetOutline(playerid, kraft[playerid][15], 0);
	PlayerTextDrawBackgroundColor(playerid, kraft[playerid][15], 0x333333FF);
	PlayerTextDrawFont(playerid, kraft[playerid][15], 5);
	PlayerTextDrawSetProportional(playerid, kraft[playerid][15], 1);
	PlayerTextDrawSetSelectable(playerid, kraft[playerid][15], 1);
	PlayerTextDrawSetPreviewModel(playerid, kraft[playerid][15], 2936);
	PlayerTextDrawSetPreviewRot(playerid, kraft[playerid][15], 154.000000, 18.000000, 220.000000, 1.063607);

	kraft[playerid][14] = CreatePlayerTextDraw(playerid, 299.750000, 290.899597, "~r~0 / 2");
	PlayerTextDrawLetterSize(playerid, kraft[playerid][14], 0.089958, 0.529030);
	PlayerTextDrawTextSize(playerid, kraft[playerid][14], 1280.000000, 1280.000000);
	PlayerTextDrawAlignment(playerid, kraft[playerid][14], 2);
	PlayerTextDrawColor(playerid, kraft[playerid][14], 0xFFFFFFFF);
	PlayerTextDrawUseBox(playerid, kraft[playerid][14], 0);
	PlayerTextDrawBoxColor(playerid, kraft[playerid][14], 0x80808080);
	PlayerTextDrawSetShadow(playerid, kraft[playerid][14], 0);
	PlayerTextDrawSetOutline(playerid, kraft[playerid][14], 0);
	PlayerTextDrawBackgroundColor(playerid, kraft[playerid][14], 0x00000000);
	PlayerTextDrawFont(playerid, kraft[playerid][14], 2);
	PlayerTextDrawSetProportional(playerid, kraft[playerid][14], 1);
	PlayerTextDrawSetSelectable(playerid, kraft[playerid][14], 0);

	kraft[playerid][13] = CreatePlayerTextDraw(playerid, 317.000000, 271.160461, "LD_SPAC:white");
	PlayerTextDrawLetterSize(playerid, kraft[playerid][13], 0.480000, 1.120000);
	PlayerTextDrawTextSize(playerid, kraft[playerid][13], 22.500000, 26.029411);
	PlayerTextDrawAlignment(playerid, kraft[playerid][13], 1);
	PlayerTextDrawColor(playerid, kraft[playerid][13], 0x666666FF);
	PlayerTextDrawUseBox(playerid, kraft[playerid][13], 0);
	PlayerTextDrawBoxColor(playerid, kraft[playerid][13], 0x80808080);
	PlayerTextDrawSetShadow(playerid, kraft[playerid][13], 2);
	PlayerTextDrawSetOutline(playerid, kraft[playerid][13], 0);
	PlayerTextDrawBackgroundColor(playerid, kraft[playerid][13], 0x333333FF);
	PlayerTextDrawFont(playerid, kraft[playerid][13], 5);
	PlayerTextDrawSetProportional(playerid, kraft[playerid][13], 1);
	PlayerTextDrawSetSelectable(playerid, kraft[playerid][13], 1);
	PlayerTextDrawSetPreviewModel(playerid, kraft[playerid][13], 19843);
	PlayerTextDrawSetPreviewRot(playerid, kraft[playerid][13], 331.000000, 0.000000, 133.000000, 1.204378);

	kraft[playerid][12] = CreatePlayerTextDraw(playerid, 328.250000, 290.899597, "~r~0 / 25");
	PlayerTextDrawLetterSize(playerid, kraft[playerid][12], 0.089958, 0.529030);
	PlayerTextDrawTextSize(playerid, kraft[playerid][12], 1280.000000, 1280.000000);
	PlayerTextDrawAlignment(playerid, kraft[playerid][12], 2);
	PlayerTextDrawColor(playerid, kraft[playerid][12], 0xFFFFFFFF);
	PlayerTextDrawUseBox(playerid, kraft[playerid][12], 0);
	PlayerTextDrawBoxColor(playerid, kraft[playerid][12], 0x80808080);
	PlayerTextDrawSetShadow(playerid, kraft[playerid][12], 0);
	PlayerTextDrawSetOutline(playerid, kraft[playerid][12], 0);
	PlayerTextDrawBackgroundColor(playerid, kraft[playerid][12], 0x00000000);
	PlayerTextDrawFont(playerid, kraft[playerid][12], 2);
	PlayerTextDrawSetProportional(playerid, kraft[playerid][12], 1);
	PlayerTextDrawSetSelectable(playerid, kraft[playerid][12], 0);

	kraft[playerid][11] = CreatePlayerTextDraw(playerid, 345.500000, 271.160461, "LD_SPAC:white");
	PlayerTextDrawLetterSize(playerid, kraft[playerid][11], 0.480000, 1.120000);
	PlayerTextDrawTextSize(playerid, kraft[playerid][11], 22.500000, 26.029411);
	PlayerTextDrawAlignment(playerid, kraft[playerid][11], 1);
	PlayerTextDrawColor(playerid, kraft[playerid][11], 0x666666FF);
	PlayerTextDrawUseBox(playerid, kraft[playerid][11], 0);
	PlayerTextDrawBoxColor(playerid, kraft[playerid][11], 0x80808080);
	PlayerTextDrawSetShadow(playerid, kraft[playerid][11], 2);
	PlayerTextDrawSetOutline(playerid, kraft[playerid][11], 0);
	PlayerTextDrawBackgroundColor(playerid, kraft[playerid][11], 0x333333FF);
	PlayerTextDrawFont(playerid, kraft[playerid][11], 5);
	PlayerTextDrawSetProportional(playerid, kraft[playerid][11], 1);
	PlayerTextDrawSetSelectable(playerid, kraft[playerid][11], 0);
	PlayerTextDrawSetPreviewModel(playerid, kraft[playerid][11], 1649);
	PlayerTextDrawSetPreviewRot(playerid, kraft[playerid][11], 0.000000, 0.000000, 90.000000, 2.000000);

	kraft[playerid][10] = CreatePlayerTextDraw(playerid, 356.750000, 290.899597, "");
	PlayerTextDrawLetterSize(playerid, kraft[playerid][10], 0.089958, 0.529030);
	PlayerTextDrawTextSize(playerid, kraft[playerid][10], 1280.000000, 1280.000000);
	PlayerTextDrawAlignment(playerid, kraft[playerid][10], 2);
	PlayerTextDrawColor(playerid, kraft[playerid][10], 0xFFFFFFFF);
	PlayerTextDrawUseBox(playerid, kraft[playerid][10], 0);
	PlayerTextDrawBoxColor(playerid, kraft[playerid][10], 0x80808080);
	PlayerTextDrawSetShadow(playerid, kraft[playerid][10], 0);
	PlayerTextDrawSetOutline(playerid, kraft[playerid][10], 0);
	PlayerTextDrawBackgroundColor(playerid, kraft[playerid][10], 0x00000000);
	PlayerTextDrawFont(playerid, kraft[playerid][10], 2);
	PlayerTextDrawSetProportional(playerid, kraft[playerid][10], 1);
	PlayerTextDrawSetSelectable(playerid, kraft[playerid][10], 0);

	kraft[playerid][9] = CreatePlayerTextDraw(playerid, 260.000000, 328.493561, "KOL-VO:");
	PlayerTextDrawLetterSize(playerid, kraft[playerid][9], 0.107949, 0.634835);
	PlayerTextDrawTextSize(playerid, kraft[playerid][9], 1280.000000, 1280.000000);
	PlayerTextDrawAlignment(playerid, kraft[playerid][9], 1);
	PlayerTextDrawColor(playerid, kraft[playerid][9], 0xDA9949FF);
	PlayerTextDrawUseBox(playerid, kraft[playerid][9], 0);
	PlayerTextDrawBoxColor(playerid, kraft[playerid][9], 0x80808080);
	PlayerTextDrawSetShadow(playerid, kraft[playerid][9], 0);
	PlayerTextDrawSetOutline(playerid, kraft[playerid][9], 0);
	PlayerTextDrawBackgroundColor(playerid, kraft[playerid][9], 0x00000000);
	PlayerTextDrawFont(playerid, kraft[playerid][9], 2);
	PlayerTextDrawSetProportional(playerid, kraft[playerid][9], 1);
	PlayerTextDrawSetSelectable(playerid, kraft[playerid][9], 0);

	kraft[playerid][8] = CreatePlayerTextDraw(playerid, 280.024597, 325.716156, "-");
	PlayerTextDrawLetterSize(playerid, kraft[playerid][8], 0.188911, 1.110962);
	PlayerTextDrawTextSize(playerid, kraft[playerid][8], 285.691925, 11.109620);
	PlayerTextDrawAlignment(playerid, kraft[playerid][8], 1);
	PlayerTextDrawColor(playerid, kraft[playerid][8], 0x777777FF);
	PlayerTextDrawUseBox(playerid, kraft[playerid][8], 0);
	PlayerTextDrawBoxColor(playerid, kraft[playerid][8], 0x80808080);
	PlayerTextDrawSetShadow(playerid, kraft[playerid][8], 0);
	PlayerTextDrawSetOutline(playerid, kraft[playerid][8], 0);
	PlayerTextDrawBackgroundColor(playerid, kraft[playerid][8], 0x00000000);
	PlayerTextDrawFont(playerid, kraft[playerid][8], 1);
	PlayerTextDrawSetProportional(playerid, kraft[playerid][8], 1);
	PlayerTextDrawSetSelectable(playerid, kraft[playerid][8], 1);

	kraft[playerid][7] = CreatePlayerTextDraw(playerid, 285.885254, 329.197235, "LD_SPAC:white");
	PlayerTextDrawLetterSize(playerid, kraft[playerid][7], 0.480000, 1.120000);
	PlayerTextDrawTextSize(playerid, kraft[playerid][7], 24.000000, 7.375000);
	PlayerTextDrawAlignment(playerid, kraft[playerid][7], 1);
	PlayerTextDrawColor(playerid, kraft[playerid][7], 0x222222FF);
	PlayerTextDrawUseBox(playerid, kraft[playerid][7], 0);
	PlayerTextDrawBoxColor(playerid, kraft[playerid][7], 0x80808080);
	PlayerTextDrawSetShadow(playerid, kraft[playerid][7], 2);
	PlayerTextDrawSetOutline(playerid, kraft[playerid][7], 0);
	PlayerTextDrawBackgroundColor(playerid, kraft[playerid][7], 0x000000FF);
	PlayerTextDrawFont(playerid, kraft[playerid][7], 4);
	PlayerTextDrawSetProportional(playerid, kraft[playerid][7], 1);
	PlayerTextDrawSetSelectable(playerid, kraft[playerid][7], 0);

	kraft[playerid][6] = CreatePlayerTextDraw(playerid, 288.885254, 329.710571, "1");
	PlayerTextDrawLetterSize(playerid, kraft[playerid][6], 0.107949, 0.634835);
	PlayerTextDrawTextSize(playerid, kraft[playerid][6], 312.885254, 6.348354);
	PlayerTextDrawAlignment(playerid, kraft[playerid][6], 1);
	PlayerTextDrawColor(playerid, kraft[playerid][6], 0x777777FF);
	PlayerTextDrawUseBox(playerid, kraft[playerid][6], 0);
	PlayerTextDrawBoxColor(playerid, kraft[playerid][6], 0x80808080);
	PlayerTextDrawSetShadow(playerid, kraft[playerid][6], 0);
	PlayerTextDrawSetOutline(playerid, kraft[playerid][6], 0);
	PlayerTextDrawBackgroundColor(playerid, kraft[playerid][6], 0x00000000);
	PlayerTextDrawFont(playerid, kraft[playerid][6], 2);
	PlayerTextDrawSetProportional(playerid, kraft[playerid][6], 1);
	PlayerTextDrawSetSelectable(playerid, kraft[playerid][6], 1);

	kraft[playerid][5] = CreatePlayerTextDraw(playerid, 312.885254, 326.993774, "+");
	PlayerTextDrawLetterSize(playerid, kraft[playerid][5], 0.167321, 0.952253);
	PlayerTextDrawTextSize(playerid, kraft[playerid][5], 317.904907, 9.522532);
	PlayerTextDrawAlignment(playerid, kraft[playerid][5], 1);
	PlayerTextDrawColor(playerid, kraft[playerid][5], 0x70A64EFF);
	PlayerTextDrawUseBox(playerid, kraft[playerid][5], 0);
	PlayerTextDrawBoxColor(playerid, kraft[playerid][5], 0x80808080);
	PlayerTextDrawSetShadow(playerid, kraft[playerid][5], 0);
	PlayerTextDrawSetOutline(playerid, kraft[playerid][5], 0);
	PlayerTextDrawBackgroundColor(playerid, kraft[playerid][5], 0x00000000);
	PlayerTextDrawFont(playerid, kraft[playerid][5], 1);
	PlayerTextDrawSetProportional(playerid, kraft[playerid][5], 1);
	PlayerTextDrawSetSelectable(playerid, kraft[playerid][5], 1);

	kraft[playerid][4] = CreatePlayerTextDraw(playerid, 260.000000, 306.189880, "~g~COST");
	PlayerTextDrawLetterSize(playerid, kraft[playerid][4], 0.107949, 0.634835);
	PlayerTextDrawTextSize(playerid, kraft[playerid][4], 1280.000000, 1280.000000);
	PlayerTextDrawAlignment(playerid, kraft[playerid][4], 1);
	PlayerTextDrawColor(playerid, kraft[playerid][4], 0x00FFFFFF);
	PlayerTextDrawUseBox(playerid, kraft[playerid][4], 0);
	PlayerTextDrawBoxColor(playerid, kraft[playerid][4], 0x80808080);
	PlayerTextDrawSetShadow(playerid, kraft[playerid][4], 0);
	PlayerTextDrawSetOutline(playerid, kraft[playerid][4], 0);
	PlayerTextDrawBackgroundColor(playerid, kraft[playerid][4], 0x00000000);
	PlayerTextDrawFont(playerid, kraft[playerid][4], 2);
	PlayerTextDrawSetProportional(playerid, kraft[playerid][4], 1);
	PlayerTextDrawSetSelectable(playerid, kraft[playerid][4], 0);

	kraft[playerid][3] = CreatePlayerTextDraw(playerid, 368.000000, 306.189880, "~g~$1000");
	PlayerTextDrawLetterSize(playerid, kraft[playerid][3], 0.107949, 0.634835);
	PlayerTextDrawTextSize(playerid, kraft[playerid][3], 1280.000000, 1280.000000);
	PlayerTextDrawAlignment(playerid, kraft[playerid][3], 3);
	PlayerTextDrawColor(playerid, kraft[playerid][3], 0xFFFFFFFF);
	PlayerTextDrawUseBox(playerid, kraft[playerid][3], 0);
	PlayerTextDrawBoxColor(playerid, kraft[playerid][3], 0x80808080);
	PlayerTextDrawSetShadow(playerid, kraft[playerid][3], 0);
	PlayerTextDrawSetOutline(playerid, kraft[playerid][3], 0);
	PlayerTextDrawBackgroundColor(playerid, kraft[playerid][3], 0x00000000);
	PlayerTextDrawFont(playerid, kraft[playerid][3], 2);
	PlayerTextDrawSetProportional(playerid, kraft[playerid][3], 1);
	PlayerTextDrawSetSelectable(playerid, kraft[playerid][3], 0);

	kraft[playerid][2] = CreatePlayerTextDraw(playerid, 314.000000, 313.982513, "SUCCESS CHANCE: 1%");
	PlayerTextDrawLetterSize(playerid, kraft[playerid][2], 0.134937, 0.793544);
	PlayerTextDrawTextSize(playerid, kraft[playerid][2], 1280.000000, 1280.000000);
	PlayerTextDrawAlignment(playerid, kraft[playerid][2], 2);
	PlayerTextDrawColor(playerid, kraft[playerid][2], 0xDA9949FF);
	PlayerTextDrawUseBox(playerid, kraft[playerid][2], 0);
	PlayerTextDrawBoxColor(playerid, kraft[playerid][2], 0x80808080);
	PlayerTextDrawSetShadow(playerid, kraft[playerid][2], 0);
	PlayerTextDrawSetOutline(playerid, kraft[playerid][2], 0);
	PlayerTextDrawBackgroundColor(playerid, kraft[playerid][2], 0x00000000);
	PlayerTextDrawFont(playerid, kraft[playerid][2], 2);
	PlayerTextDrawSetProportional(playerid, kraft[playerid][2], 1);
	PlayerTextDrawSetSelectable(playerid, kraft[playerid][2], 0);

	kraft[playerid][1] = CreatePlayerTextDraw(playerid, 323.319275, 326.247223, "LD_SPAC:white");
	PlayerTextDrawLetterSize(playerid, kraft[playerid][1], 0.480000, 1.120000);
	PlayerTextDrawTextSize(playerid, kraft[playerid][1], 47.680725, 13.325012);
	PlayerTextDrawAlignment(playerid, kraft[playerid][1], 1);
	PlayerTextDrawColor(playerid, kraft[playerid][1], PI[playerid][pColorInv]);
	PlayerTextDrawUseBox(playerid, kraft[playerid][1], 0);
	PlayerTextDrawBoxColor(playerid, kraft[playerid][1], 0x80808080);
	PlayerTextDrawSetShadow(playerid, kraft[playerid][1], 2);
	PlayerTextDrawSetOutline(playerid, kraft[playerid][1], 0);
	PlayerTextDrawBackgroundColor(playerid, kraft[playerid][1], 0x000000FF);
	PlayerTextDrawFont(playerid, kraft[playerid][1], 4);
	PlayerTextDrawSetProportional(playerid, kraft[playerid][1], 1);
	PlayerTextDrawSetSelectable(playerid, kraft[playerid][1], 0);

	if(PI[playerid][pInvLang] == 0) kraft[playerid][0] = CreatePlayerTextDraw(playerid, 347.159637, 329.735565, "CRAFT");
	else kraft[playerid][0] = CreatePlayerTextDraw(playerid, 347.159637, 329.735565, FixText("KPAЃT"));
	PlayerTextDrawLetterSize(playerid, kraft[playerid][0], 0.107949, 0.634835);
	PlayerTextDrawTextSize(playerid, kraft[playerid][0], 1280.000000, 1280.000000);
	PlayerTextDrawAlignment(playerid, kraft[playerid][0], 2);
	PlayerTextDrawColor(playerid, kraft[playerid][0], 0xFFFFFFFF);
	PlayerTextDrawUseBox(playerid, kraft[playerid][0], 0);
	PlayerTextDrawBoxColor(playerid, kraft[playerid][0], 0x80808080);
	PlayerTextDrawSetShadow(playerid, kraft[playerid][0], 0);
	PlayerTextDrawSetOutline(playerid, kraft[playerid][0], 0);
	PlayerTextDrawBackgroundColor(playerid, kraft[playerid][0], 0x00000000);
	PlayerTextDrawFont(playerid, kraft[playerid][0], 2);
	PlayerTextDrawSetProportional(playerid, kraft[playerid][0], 1);
	PlayerTextDrawSetSelectable(playerid, kraft[playerid][0], 0);
    if(kraftstr{playerid} == 2)
	{
	    PlayerTextDrawSetSelectable(playerid, kraft[playerid][49], 1);
	    PlayerTextDrawColor(playerid, kraft[playerid][49], 0x777777FF);
	}
	if(kraftstr{playerid} == 4)
	{
	    PlayerTextDrawSetSelectable(playerid, kraft[playerid][47], 1);
	    PlayerTextDrawColor(playerid, kraft[playerid][47], 0x777777FF);
	}
    PlayerTextDrawSetSelectable(playerid, kraft[playerid][50], 0);
    PlayerTextDrawColor(playerid, kraft[playerid][50], 0xDA9949FF);
    PlayerTextDrawHide(playerid, kraft[playerid][49]);
    PlayerTextDrawShow(playerid, kraft[playerid][49]);
    PlayerTextDrawHide(playerid, kraft[playerid][50]);
    PlayerTextDrawShow(playerid, kraft[playerid][50]);
    PlayerTextDrawSetString(playerid, kraft[playerid][45], "Kolonka");
    PlayerTextDrawSetString(playerid, kraft[playerid][43], "Extinguisher");
    PlayerTextDrawSetString(playerid, kraft[playerid][41], "Bat with nails");
    PlayerTextDrawSetString(playerid, kraft[playerid][39], "Sword");
    PlayerTextDrawSetString(playerid, kraft[playerid][37], "Hammer");
    PlayerTextDrawSetString(playerid, kraft[playerid][35], "Maska CJ");
    PlayerTextDrawSetString(playerid, kraft[playerid][33], "Red suitcase");
    PlayerTextDrawSetString(playerid, kraft[playerid][31], "Helmet");
    PlayerTextDrawSetString(playerid, kraft[playerid][2], "SUCCESS CHANCE: 1%");
    kraftcena[playerid] = 1000;
    kraftcenanew[playerid] = 1000;
    PlayerTextDrawSetString(playerid, kraft[playerid][3], "~g~$1000");
	PlayerTextDrawSetString(playerid, kraft[playerid][24], "1 / 2");
    PlayerTextDrawSetPreviewModel(playerid, kraft[playerid][13], 19843);
    PlayerTextDrawSetPreviewRot(playerid, kraft[playerid][13], 331.000000, 0.000000, 133.000000, 1.204378);
    PlayerTextDrawHide(playerid, kraft[playerid][13]);
    PlayerTextDrawShow(playerid, kraft[playerid][13]);
	PlayerTextDrawSetPreviewModel(playerid, kraft[playerid][17], 1304);
	PlayerTextDrawSetPreviewRot(playerid, kraft[playerid][17], 236.000000, 0.000000, 0.000000, 1.558915);
    PlayerTextDrawHide(playerid, kraft[playerid][17]);
    PlayerTextDrawShow(playerid, kraft[playerid][17]);
	PlayerTextDrawSetPreviewRot(playerid, kraft[playerid][15], 154.000000, 18.000000, 220.000000, 1.063607);
	PlayerTextDrawSetPreviewRot(playerid, kraft[playerid][21], 0.000000, 0.000000, 193.000000, 0.872784);
	PlayerTextDrawSetString(playerid, kraft[playerid][20], "Kolonka");
	PlayerTextDrawSetPreviewModel(playerid, kraft[playerid][21], 2102);
	PlayerTextDrawColor(playerid, kraft[playerid][46], PI[playerid][pColorInv]);
	PlayerTextDrawColor(playerid, kraft[playerid][45], 0xFFFFFFFF);
	if(kraftitem{playerid} == 2 || kraftitem{playerid} == 12 || kraftitem{playerid} == 18 || kraftitem{playerid} == 26)
	{
		PlayerTextDrawColor(playerid, kraft[playerid][43], 0x777777FF);
		PlayerTextDrawSetSelectable(playerid, kraft[playerid][43], 67);
		PlayerTextDrawColor(playerid, kraft[playerid][44], 0x050505FF);
	}
	if(kraftitem{playerid} == 3 || kraftitem{playerid} == 13 || kraftitem{playerid} == 19 || kraftitem{playerid} == 27)
	{
		PlayerTextDrawColor(playerid, kraft[playerid][41], 0x777777FF);
		PlayerTextDrawSetSelectable(playerid, kraft[playerid][41], 67);
		PlayerTextDrawColor(playerid, kraft[playerid][42], 0x050505FF);
	}
	if(kraftitem{playerid} == 4 || kraftitem{playerid} == 14 || kraftitem{playerid} == 20 || kraftitem{playerid} == 28)
	{
		PlayerTextDrawColor(playerid, kraft[playerid][39], 0x777777FF);
		PlayerTextDrawSetSelectable(playerid, kraft[playerid][39], 67);
		PlayerTextDrawColor(playerid, kraft[playerid][40], 0x050505FF);
	}
	if(kraftitem{playerid} == 5 || kraftitem{playerid} == 15 || kraftitem{playerid} == 21 || kraftitem{playerid} == 29)
	{
		PlayerTextDrawColor(playerid, kraft[playerid][37], 0x777777FF);
		PlayerTextDrawSetSelectable(playerid, kraft[playerid][37], 67);
		PlayerTextDrawColor(playerid, kraft[playerid][38], 0x050505FF);
	}
	if(kraftitem{playerid} == 6 || kraftitem{playerid} == 16 || kraftitem{playerid} == 22)
	{
		PlayerTextDrawColor(playerid, kraft[playerid][35], 0x777777FF);
		PlayerTextDrawSetSelectable(playerid, kraft[playerid][35], 67);
		PlayerTextDrawColor(playerid, kraft[playerid][36], 0x050505FF);
	}
	if(kraftitem{playerid} == 7 || kraftitem{playerid} == 23)
	{
		PlayerTextDrawColor(playerid, kraft[playerid][33], 0x777777FF);
		PlayerTextDrawSetSelectable(playerid, kraft[playerid][33], 67);
		PlayerTextDrawColor(playerid, kraft[playerid][34], 0x050505FF);
	}
	if(kraftitem{playerid} == 8 || kraftitem{playerid} == 24)
	{
		PlayerTextDrawColor(playerid, kraft[playerid][31], 0x777777FF);
		PlayerTextDrawSetSelectable(playerid, kraft[playerid][31], 67);
		PlayerTextDrawColor(playerid, kraft[playerid][32], 0x050505FF);
	}
	if(kraftitem{playerid} == 9)
	{
		PlayerTextDrawColor(playerid, kraft[playerid][29], 0x777777FF);
		PlayerTextDrawSetSelectable(playerid, kraft[playerid][29], 67);
		PlayerTextDrawColor(playerid, kraft[playerid][30], 0x050505FF);
	}
	if(kraftitem{playerid} == 10)
	{
		PlayerTextDrawColor(playerid, kraft[playerid][27], 0x777777FF);
		PlayerTextDrawSetSelectable(playerid, kraft[playerid][27], 67);
		PlayerTextDrawColor(playerid, kraft[playerid][28], 0x050505FF);
	}
	PlayerTextDrawSetSelectable(playerid, kraft[playerid][45], 0);
	if(GetCount(playerid, 346) >= 30 && GetCount(playerid, 345) >= 2 && GetCount(playerid, 346) >= 25) PlayerTextDrawColor(playerid, kraft[playerid][1], 0x6FBE55FF), PlayerTextDrawSetSelectable(playerid, kraft[playerid][1], 1);
	else
	{
		PlayerTextDrawColor(playerid, kraft[playerid][1], 0xBE6955FF);
		PlayerTextDrawSetSelectable(playerid, kraft[playerid][1], 0);
	}
	HideInventory(playerid);
	HideBoom(playerid);
	PlayerTextDrawSetPreviewModel(playerid, kraft[playerid][15], 2936);
 	for(new i; i < 9; i++) {
 		DestroyPlayerTD(playerid, uvedomlenie[playerid][i]);
 	}
	if(donateopen{playerid}){
		HideDonate(playerid);
	}
	for(new i; i < 54; i++) PlayerTextDrawShow(playerid, kraft[playerid][i]);
	SelectTextDraw(playerid, PI[playerid][pColorInv]);
	kraftraz[playerid] =
	kraftshanc{playerid} =
	kraftstr{playerid} = 1;
	kraftitem{playerid} = 1;
    kraftcena[playerid] =
    kraftcenanew[playerid] = 1000;
	kraftmetall[playerid] = 30;
	kraftbronza[playerid] = 2;
	kraftmats[playerid] = 25;
	new string[20];
	format(string, sizeof(string), "%s%i / 30", (GetCount(playerid, 346) >= 30) ? ("~g~") : ("~r~"), GetCount(playerid, 346));
	PlayerTextDrawSetString(playerid, kraft[playerid][16], string);
	format(string, sizeof(string), "%s%i / 2", (GetCount(playerid, 345) >= 2) ? ("~g~") : ("~r~"), GetCount(playerid, 345));
    PlayerTextDrawSetString(playerid, kraft[playerid][14], string);
	format(string, sizeof(string), "%s%i / 25", (GetCount(playerid, 346) >= 25) ? ("~g~") : ("~r~"), GetCount(playerid, 346));
	PlayerTextDrawSetString(playerid, kraft[playerid][12], string);
    if(GetCount(playerid, 346) >= 30) PlayerTextDrawColor(playerid, kraft[playerid][17], 0xFFFFFFFF);
    else PlayerTextDrawColor(playerid, kraft[playerid][17], 0x666666FF);
    if(GetCount(playerid, 345) >= 2) PlayerTextDrawColor(playerid, kraft[playerid][15], 0xFFFFFFFF);
    else PlayerTextDrawColor(playerid, kraft[playerid][15], 0x666666FF);
    if(GetCount(playerid, 346) >= 25) PlayerTextDrawColor(playerid, kraft[playerid][13], 0xFFFFFFFF);
    else PlayerTextDrawColor(playerid, kraft[playerid][13], 0x666666FF);
    PlayerTextDrawHide(playerid, kraft[playerid][17]);
    PlayerTextDrawShow(playerid, kraft[playerid][17]);
    PlayerTextDrawHide(playerid, kraft[playerid][15]);
    PlayerTextDrawShow(playerid, kraft[playerid][15]);
    PlayerTextDrawHide(playerid, kraft[playerid][13]);
    PlayerTextDrawShow(playerid, kraft[playerid][13]);
	PlayerTextDrawSetString(playerid, kraft[playerid][3], "~g~$1000");
	PlayerTextDrawSetString(playerid, kraft[playerid][6], "1");
	if(kraftplus{playerid}) {
	    PlayerTextDrawDestroy(playerid, kraft[playerid][54]);
	    PlayerTextDrawDestroy(playerid, kraft[playerid][55]);
	    kraftplus{playerid} = false;
	}