tdshar_TD_PTD[playerid][0] = CreatePlayerTextDraw(playerid, 228.3332, 265.0813, "Box"); // пусто
PlayerTextDrawLetterSize(playerid, tdshar_TD_PTD[playerid][0], 0.0000, -9.7333);
PlayerTextDrawTextSize(playerid, tdshar_TD_PTD[playerid][0], 408.0000, 0.0000);
PlayerTextDrawAlignment(playerid, tdshar_TD_PTD[playerid][0], 1);
PlayerTextDrawColor(playerid, tdshar_TD_PTD[playerid][0], -1);
PlayerTextDrawUseBox(playerid, tdshar_TD_PTD[playerid][0], 1);
PlayerTextDrawBoxColor(playerid, tdshar_TD_PTD[playerid][0], 437918463);
PlayerTextDrawBackgroundColor(playerid, tdshar_TD_PTD[playerid][0], -2139062017);
PlayerTextDrawFont(playerid, tdshar_TD_PTD[playerid][0], 1);
PlayerTextDrawSetProportional(playerid, tdshar_TD_PTD[playerid][0], 1);
PlayerTextDrawSetShadow(playerid, tdshar_TD_PTD[playerid][0], 0);

tdshar_TD_PTD[playerid][1] = CreatePlayerTextDraw(playerid, 228.3332, 231.8963, "Box"); // пусто
PlayerTextDrawLetterSize(playerid, tdshar_TD_PTD[playerid][1], 0.0000, 2.4000);
PlayerTextDrawTextSize(playerid, tdshar_TD_PTD[playerid][1], 408.0000, 0.0000);
PlayerTextDrawAlignment(playerid, tdshar_TD_PTD[playerid][1], 1);
PlayerTextDrawColor(playerid, tdshar_TD_PTD[playerid][1], -1);
PlayerTextDrawUseBox(playerid, tdshar_TD_PTD[playerid][1], 1);
PlayerTextDrawBoxColor(playerid, tdshar_TD_PTD[playerid][1], PI[playerid][pColorInv]);//1884938239
PlayerTextDrawBackgroundColor(playerid, tdshar_TD_PTD[playerid][1], 255);
PlayerTextDrawFont(playerid, tdshar_TD_PTD[playerid][1], 1);
PlayerTextDrawSetProportional(playerid, tdshar_TD_PTD[playerid][1], 1);
PlayerTextDrawSetShadow(playerid, tdshar_TD_PTD[playerid][1], 0);

tdshar_TD_PTD[playerid][2] = CreatePlayerTextDraw(playerid, 266.9999, 234.8000, "PRESSED"); // пусто
PlayerTextDrawLetterSize(playerid, tdshar_TD_PTD[playerid][2], 0.3472, 2.1558);
PlayerTextDrawAlignment(playerid, tdshar_TD_PTD[playerid][2], 1);
PlayerTextDrawColor(playerid, tdshar_TD_PTD[playerid][2], -1);
PlayerTextDrawBackgroundColor(playerid, tdshar_TD_PTD[playerid][2], 255);
PlayerTextDrawFont(playerid, tdshar_TD_PTD[playerid][2], 2);
PlayerTextDrawSetProportional(playerid, tdshar_TD_PTD[playerid][2], 1);
PlayerTextDrawSetShadow(playerid, tdshar_TD_PTD[playerid][2], 0);

tdshar_TD_PTD[playerid][3] = CreatePlayerTextDraw(playerid, 324.3331, 237.2888, "(______"); // пусто
PlayerTextDrawLetterSize(playerid, tdshar_TD_PTD[playerid][3], 0.2159, 1.2058);
PlayerTextDrawAlignment(playerid, tdshar_TD_PTD[playerid][3], 1);
PlayerTextDrawColor(playerid, tdshar_TD_PTD[playerid][3], -1);
PlayerTextDrawBackgroundColor(playerid, tdshar_TD_PTD[playerid][3], 255);
PlayerTextDrawFont(playerid, tdshar_TD_PTD[playerid][3], 3);
PlayerTextDrawSetProportional(playerid, tdshar_TD_PTD[playerid][3], 1);
PlayerTextDrawSetShadow(playerid, tdshar_TD_PTD[playerid][3], 0);

tdshar_TD_PTD[playerid][4] = CreatePlayerTextDraw(playerid, 328.6665, 234.3851, ""); // пусто
PlayerTextDrawLetterSize(playerid, tdshar_TD_PTD[playerid][4], 0.3786, 2.1682);
PlayerTextDrawAlignment(playerid, tdshar_TD_PTD[playerid][4], 1);
PlayerTextDrawColor(playerid, tdshar_TD_PTD[playerid][4], 811310591);
PlayerTextDrawBackgroundColor(playerid, tdshar_TD_PTD[playerid][4], 255);
PlayerTextDrawFont(playerid, tdshar_TD_PTD[playerid][4], 2);
PlayerTextDrawSetProportional(playerid, tdshar_TD_PTD[playerid][4], 1);
PlayerTextDrawSetShadow(playerid, tdshar_TD_PTD[playerid][4], 0);

tdshar_TD_PTD[playerid][5] = CreatePlayerTextDraw(playerid, 344.6665, 237.2888, "(______"); // пусто
PlayerTextDrawLetterSize(playerid, tdshar_TD_PTD[playerid][5], -0.1826, 1.2182);
PlayerTextDrawAlignment(playerid, tdshar_TD_PTD[playerid][5], 1);
PlayerTextDrawColor(playerid, tdshar_TD_PTD[playerid][5], -1);
PlayerTextDrawBackgroundColor(playerid, tdshar_TD_PTD[playerid][5], 255);
PlayerTextDrawFont(playerid, tdshar_TD_PTD[playerid][5], 3);
PlayerTextDrawSetProportional(playerid, tdshar_TD_PTD[playerid][5], 1);
PlayerTextDrawSetShadow(playerid, tdshar_TD_PTD[playerid][5], 0);

tdshar_TD_PTD[playerid][6] = CreatePlayerTextDraw(playerid, 226.7333, 203.5036, "LD_BEAT:Chit"); // пусто
PlayerTextDrawTextSize(playerid, tdshar_TD_PTD[playerid][6], 25.0000, 22.0000);
PlayerTextDrawAlignment(playerid, tdshar_TD_PTD[playerid][6], 1);
PlayerTextDrawColor(playerid, tdshar_TD_PTD[playerid][6], PI[playerid][pColorInv]);//1884938239
PlayerTextDrawBackgroundColor(playerid, tdshar_TD_PTD[playerid][6], 255);
PlayerTextDrawFont(playerid, tdshar_TD_PTD[playerid][6], 4);
PlayerTextDrawSetProportional(playerid, tdshar_TD_PTD[playerid][6], 0);
PlayerTextDrawSetShadow(playerid, tdshar_TD_PTD[playerid][6], 0);

tdshar_TD_PTD[playerid][7] = CreatePlayerTextDraw(playerid, 239.6665, 208.7518, "Box"); // пусто
PlayerTextDrawLetterSize(playerid, tdshar_TD_PTD[playerid][7], 0.0000, 1.2646);
PlayerTextDrawTextSize(playerid, tdshar_TD_PTD[playerid][7], 398.0000, 0.0000);
PlayerTextDrawAlignment(playerid, tdshar_TD_PTD[playerid][7], 1);
PlayerTextDrawColor(playerid, tdshar_TD_PTD[playerid][7], -1);
PlayerTextDrawUseBox(playerid, tdshar_TD_PTD[playerid][7], 1);
PlayerTextDrawBoxColor(playerid, tdshar_TD_PTD[playerid][7], PI[playerid][pColorInv]);//1884938239
PlayerTextDrawBackgroundColor(playerid, tdshar_TD_PTD[playerid][7], 255);
PlayerTextDrawFont(playerid, tdshar_TD_PTD[playerid][7], 1);
PlayerTextDrawSetProportional(playerid, tdshar_TD_PTD[playerid][7], 1);
PlayerTextDrawSetShadow(playerid, tdshar_TD_PTD[playerid][7], 0);

tdshar_TD_PTD[playerid][8] = CreatePlayerTextDraw(playerid, 385.3999, 203.5332, "LD_BEAT:Chit"); // пусто
PlayerTextDrawTextSize(playerid, tdshar_TD_PTD[playerid][8], 25.0000, 22.0000);
PlayerTextDrawAlignment(playerid, tdshar_TD_PTD[playerid][8], 1);
PlayerTextDrawColor(playerid, tdshar_TD_PTD[playerid][8], PI[playerid][pColorInv]);//1884938239
PlayerTextDrawBackgroundColor(playerid, tdshar_TD_PTD[playerid][8], 255);
PlayerTextDrawFont(playerid, tdshar_TD_PTD[playerid][8], 4);
PlayerTextDrawSetProportional(playerid, tdshar_TD_PTD[playerid][8], 0);
PlayerTextDrawSetShadow(playerid, tdshar_TD_PTD[playerid][8], 0);

tdshar_TD_PTD[playerid][9] = CreatePlayerTextDraw(playerid, 237.6665, 191.6591, "0%_TO_COMPILE"); // пусто
PlayerTextDrawLetterSize(playerid, tdshar_TD_PTD[playerid][9], 0.1640, 0.8324);
PlayerTextDrawAlignment(playerid, tdshar_TD_PTD[playerid][9], 1);
PlayerTextDrawColor(playerid, tdshar_TD_PTD[playerid][9], -1);
PlayerTextDrawBackgroundColor(playerid, tdshar_TD_PTD[playerid][9], 255);
PlayerTextDrawFont(playerid, tdshar_TD_PTD[playerid][9], 1);
PlayerTextDrawSetProportional(playerid, tdshar_TD_PTD[playerid][9], 1);
PlayerTextDrawSetShadow(playerid, tdshar_TD_PTD[playerid][9], 0);

tdshar_TD_PTD[playerid][10] = CreatePlayerTextDraw(playerid, 240.0666, 183.3925, "YOUR_PROGRESS"); // пусто
PlayerTextDrawLetterSize(playerid, tdshar_TD_PTD[playerid][10], 0.1325, 0.8865);
PlayerTextDrawAlignment(playerid, tdshar_TD_PTD[playerid][10], 1);
PlayerTextDrawColor(playerid, tdshar_TD_PTD[playerid][10], -1650745601);
PlayerTextDrawBackgroundColor(playerid, tdshar_TD_PTD[playerid][10], 255);
PlayerTextDrawFont(playerid, tdshar_TD_PTD[playerid][10], 1);
PlayerTextDrawSetProportional(playerid, tdshar_TD_PTD[playerid][10], 1);
PlayerTextDrawSetShadow(playerid, tdshar_TD_PTD[playerid][10], 0);

tdshar_TD_PTD[playerid][11] = CreatePlayerTextDraw(playerid, 328.6665, 234.3851, ""); // пусто
PlayerTextDrawLetterSize(playerid, tdshar_TD_PTD[playerid][11], 0.3786, 2.1682);
PlayerTextDrawAlignment(playerid, tdshar_TD_PTD[playerid][11], 1);
PlayerTextDrawColor(playerid, tdshar_TD_PTD[playerid][11], 811310591);
PlayerTextDrawBackgroundColor(playerid, tdshar_TD_PTD[playerid][11], 255);
PlayerTextDrawFont(playerid, tdshar_TD_PTD[playerid][11], 2);
PlayerTextDrawSetProportional(playerid, tdshar_TD_PTD[playerid][11], 1);
PlayerTextDrawSetShadow(playerid, tdshar_TD_PTD[playerid][11], 0);

tdshar_TD_PTD[playerid][12] = CreatePlayerTextDraw(playerid, 226.7333, 203.5036, "LD_BEAT:Chit"); // пусто
PlayerTextDrawTextSize(playerid, tdshar_TD_PTD[playerid][12], 25.0000, 22.0000);
PlayerTextDrawAlignment(playerid, tdshar_TD_PTD[playerid][12], 1);
PlayerTextDrawColor(playerid, tdshar_TD_PTD[playerid][12], -16776961);
PlayerTextDrawBackgroundColor(playerid, tdshar_TD_PTD[playerid][12], 255);
PlayerTextDrawFont(playerid, tdshar_TD_PTD[playerid][12], 4);
PlayerTextDrawSetProportional(playerid, tdshar_TD_PTD[playerid][12], 0);
PlayerTextDrawSetShadow(playerid, tdshar_TD_PTD[playerid][12], 0);

tdshar_TD_PTD[playerid][13] = CreatePlayerTextDraw(playerid, 239.6665, 208.7518, "Box"); // пусто
PlayerTextDrawLetterSize(playerid, tdshar_TD_PTD[playerid][13], 0.0000, 1.2646);
PlayerTextDrawTextSize(playerid, tdshar_TD_PTD[playerid][13], 247.0000, 0.0000);
PlayerTextDrawAlignment(playerid, tdshar_TD_PTD[playerid][13], 1);
PlayerTextDrawColor(playerid, tdshar_TD_PTD[playerid][13], -16776961);
PlayerTextDrawUseBox(playerid, tdshar_TD_PTD[playerid][13], 1);
PlayerTextDrawBoxColor(playerid, tdshar_TD_PTD[playerid][13], -16776961);
PlayerTextDrawBackgroundColor(playerid, tdshar_TD_PTD[playerid][13], 255);
PlayerTextDrawFont(playerid, tdshar_TD_PTD[playerid][13], 1);
PlayerTextDrawSetProportional(playerid, tdshar_TD_PTD[playerid][13], 1);
PlayerTextDrawSetShadow(playerid, tdshar_TD_PTD[playerid][13], 0);

tdshar_TD_PTD[playerid][14] = CreatePlayerTextDraw(playerid, 249.3332, 208.7518, "Box"); // пусто
PlayerTextDrawLetterSize(playerid, tdshar_TD_PTD[playerid][14], 0.0000, 1.2646);
PlayerTextDrawTextSize(playerid, tdshar_TD_PTD[playerid][14], 282.0000, 0.0000);
PlayerTextDrawAlignment(playerid, tdshar_TD_PTD[playerid][14], 1);
PlayerTextDrawColor(playerid, tdshar_TD_PTD[playerid][14], -16776961);
PlayerTextDrawUseBox(playerid, tdshar_TD_PTD[playerid][14], 1);
PlayerTextDrawBoxColor(playerid, tdshar_TD_PTD[playerid][14], -16776961);
PlayerTextDrawBackgroundColor(playerid, tdshar_TD_PTD[playerid][14], 255);
PlayerTextDrawFont(playerid, tdshar_TD_PTD[playerid][14], 1);
PlayerTextDrawSetProportional(playerid, tdshar_TD_PTD[playerid][14], 1);
PlayerTextDrawSetShadow(playerid, tdshar_TD_PTD[playerid][14], 0);

tdshar_TD_PTD[playerid][15] = CreatePlayerTextDraw(playerid, 284.6665, 208.7518, "Box"); // пусто
PlayerTextDrawLetterSize(playerid, tdshar_TD_PTD[playerid][15], 0.0000, 1.2646);
PlayerTextDrawTextSize(playerid, tdshar_TD_PTD[playerid][15], 336.0000, 0.0000);
PlayerTextDrawAlignment(playerid, tdshar_TD_PTD[playerid][15], 1);
PlayerTextDrawColor(playerid, tdshar_TD_PTD[playerid][15], -16776961);
PlayerTextDrawUseBox(playerid, tdshar_TD_PTD[playerid][15], 1);
PlayerTextDrawBoxColor(playerid, tdshar_TD_PTD[playerid][15], -16776961);
PlayerTextDrawBackgroundColor(playerid, tdshar_TD_PTD[playerid][15], 255);
PlayerTextDrawFont(playerid, tdshar_TD_PTD[playerid][15], 1);
PlayerTextDrawSetProportional(playerid, tdshar_TD_PTD[playerid][15], 1);
PlayerTextDrawSetShadow(playerid, tdshar_TD_PTD[playerid][15], 0);

tdshar_TD_PTD[playerid][16] = CreatePlayerTextDraw(playerid, 338.6665, 208.7518, "Box"); // пусто
PlayerTextDrawLetterSize(playerid, tdshar_TD_PTD[playerid][16], 0.0000, 1.2646);
PlayerTextDrawTextSize(playerid, tdshar_TD_PTD[playerid][16], 395.0000, 0.0000);
PlayerTextDrawAlignment(playerid, tdshar_TD_PTD[playerid][16], 1);
PlayerTextDrawColor(playerid, tdshar_TD_PTD[playerid][16], -16776961);
PlayerTextDrawUseBox(playerid, tdshar_TD_PTD[playerid][16], 1);
PlayerTextDrawBoxColor(playerid, tdshar_TD_PTD[playerid][16], -16776961);
PlayerTextDrawBackgroundColor(playerid, tdshar_TD_PTD[playerid][16], 255);
PlayerTextDrawFont(playerid, tdshar_TD_PTD[playerid][16], 1);
PlayerTextDrawSetProportional(playerid, tdshar_TD_PTD[playerid][16], 1);
PlayerTextDrawSetShadow(playerid, tdshar_TD_PTD[playerid][16], 0);

tdshar_TD_PTD[playerid][17] = CreatePlayerTextDraw(playerid, 385.3999, 203.5332, "LD_BEAT:Chit"); // пусто
PlayerTextDrawTextSize(playerid, tdshar_TD_PTD[playerid][17], 25.0000, 22.0000);
PlayerTextDrawAlignment(playerid, tdshar_TD_PTD[playerid][17], 1);
PlayerTextDrawColor(playerid, tdshar_TD_PTD[playerid][17], -16776961);
PlayerTextDrawBackgroundColor(playerid, tdshar_TD_PTD[playerid][17], 255);
PlayerTextDrawFont(playerid, tdshar_TD_PTD[playerid][17], 4);
PlayerTextDrawSetProportional(playerid, tdshar_TD_PTD[playerid][17], 0);
PlayerTextDrawSetShadow(playerid, tdshar_TD_PTD[playerid][17], 0);

sharvibor_TD[playerid][0] = CreatePlayerTextDraw(playerid, 328.6665, 234.3852, "SPACE"); // пусто
PlayerTextDrawLetterSize(playerid, sharvibor_TD[playerid][0], 0.3786, 2.1682);
PlayerTextDrawAlignment(playerid, sharvibor_TD[playerid][0], 1);
PlayerTextDrawColor(playerid, sharvibor_TD[playerid][0], 811310591);
PlayerTextDrawBackgroundColor(playerid, sharvibor_TD[playerid][0], 255);
PlayerTextDrawFont(playerid, sharvibor_TD[playerid][0], 2);
PlayerTextDrawSetProportional(playerid, sharvibor_TD[playerid][0], 1);
PlayerTextDrawSetShadow(playerid, sharvibor_TD[playerid][0], 0);

sharvibor_TD[playerid][1] = CreatePlayerTextDraw(playerid, 328.6665, 234.3852, "N"); // пусто
PlayerTextDrawLetterSize(playerid, sharvibor_TD[playerid][1], 0.3786, 2.1682);
PlayerTextDrawAlignment(playerid, sharvibor_TD[playerid][1], 1);
PlayerTextDrawColor(playerid, sharvibor_TD[playerid][1], 811310591);
PlayerTextDrawBackgroundColor(playerid, sharvibor_TD[playerid][1], 255);
PlayerTextDrawFont(playerid, sharvibor_TD[playerid][1], 2);
PlayerTextDrawSetProportional(playerid, sharvibor_TD[playerid][1], 1);
PlayerTextDrawSetShadow(playerid, sharvibor_TD[playerid][1], 0);
